services:
  app:
    ports: ["5000:5000"]
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGPASSWORD: "q1w2e3r4"
      PGUSER: "postgres"
    build:
      context: .
      dockerfile: dockerfile

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "q1w2e3r4"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "ong"
    healthcheck:
      test: pg_isready -U postgres -d ong
      interval: 10s
      timeout: 3s
      retries: 3
